### ISSUE TITLE
Another Python loudness project

### ISSUE THREAD

**Issue by hiccup7** [BrechtDeMan/loudness.py#1]
To save you effort, you may be interested in another Python project to measure loudness:
https://github.com/csteinmetz1/pyloudnorm

**Comment by BrechtDeMan** [comment]
Thanks! Didn't know Christian made this (@csteinmetz1) 😊 
However, this is a placeholder for an AES145 paper that's been in the works for a while - should be published soon and I'll upload the code shortly. Part of the point is the derivation of exact parameters that correspond with the 44.1 kHz filter coefficients in the ITU-R BS.1770 standard. The basic 'Audio EQ Cookbook' equations don't result in these exact values (though I also show the deviation is small enough for most purposes I can think of). 

It looks like Christian's also includes other filters (like the Fenton/Lee ones) and loudness normalisation. So I think there's a place for both implementations!
